version: '3.9'

services:

  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bdcafe
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  fuseki:
    image: stain/jena-fuseki:4.8.0
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin123
      - JVM_ARGS=-Xmx1g
    volumes:
      - fuseki_data:/fuseki
      - ./cafeAPI/CafeV9_Final.rdf:/staging/CafeV9_Final.rdf:ro
      - ./cafeAPI/fuseki_init.sh:/docker-entrypoint-initdb.d/fuseki_init.sh:ro
    restart: always

  cafeapi:
    build: ./cafeAPI
    container_name: cafeapi
    ports:
      - "8001:8001"
    env_file:
      - ./cafeAPI/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bdcafe
      - FUSEKI_URL=http://fuseki:3030
      - FUSEKI_DATASET=cafe
    volumes:
      - rdf_data:/app/rdf
    depends_on:
      - db
      - fuseki
    restart: always

  django:
    build: ./proyectoCafe/proyectoCafe
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - ./cafeAPI/.env
    environment:
      - DJANGO_SETTINGS_MODULE=proyectoCafe.settings_azure
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,20.109.106.76,sigic.redhub.online
      - FASTAPI_URL=http://cafeapi:8001
      - DJANGO_SECRET_KEY=cambia-esto-por-una-clave-segura
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bdcafe
    depends_on:
      - cafeapi
      - db
    restart: always

volumes:
  postgres_data:
  rdf_data:
  fuseki_data: